name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
