name: 🛂 CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: ⚗️ Lint, typecheck and format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18]
    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@v3

      - name: 🛸 Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: 🏭 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🏗️ Build packages
        run: pnpm run build

      - name: 🩻 Check types
        run: pnpm run types

      - name: 🔬 Lint files
        run: pnpm run lint

      - name: 🧬 Format files
        run: pnpm run format
